import numpy as np
import pathlib
import subprocess

module_path = pathlib.Path(np.__file__).parent / "core/_multiarray_umath.cpython-312-darwin.so"

def iter_objdump(objdump):
    header = True
    for line in objdump.splitlines():
        if line.startswith("Disassembly of section"):
            header = False
            continue
        if header or not line:
            continue
        if line.strip().endswith(":"):
            [addr, name] = line.strip().split()
            assert name.startswith("<") and name.endswith(">:")
            yield addr, f"{name[1:-2]}:"
            continue
        [addr, _machine_code_hex, astext] = line.split(maxsplit=2)
        assert addr.endswith(":")
        yield addr[:-1], astext.strip()

def parse_jump(txt):
    if not txt.startswith("b") or txt[1:2] not in ". \t":
        return
    [opcode, offset, comment] = txt.split()
    assert offset.startswith("0x") and comment.startswith("<") and comment.endswith(">")
    return {
        "opcode": opcode,
        "offset": offset[2:],
        "label": comment[1:-1].replace("+0x", "_").lower(),
    }

def gen_asm_from_objdump(objdump):
    labels = {}

    for _, txt in iter_objdump(objdump):
        j = parse_jump(txt)
        if j is None:
            continue
        labels[j["offset"]] = j["label"]

    indent = "    "
    for addr, txt in iter_objdump(objdump):
        label = labels.get(addr)
        if label is not None:
            yield f"{label}:"
        if txt.endswith(":"):
            yield txt.lower()
            continue
        j = parse_jump(txt)
        if j is None:
            yield indent + txt.replace("\t", " ")
        else:
            yield indent + j['opcode'] + " " + j["label"]

header = """
// Auto-generated by extract-func-asm.py
// NOTE: This is actually the compiled code from numpy, so it inherits numpy's BSD license.

""".lstrip()

if __name__ == "__main__":
    objdump = subprocess.run(
        ["objdump", "--disassemble-symbols=_CDOUBLE_square", module_path],
        stdout=subprocess.PIPE,
        ).stdout.decode('utf-8')
    result = "\n".join(gen_asm_from_objdump(objdump))
    # Replace specific constant stored in specific place in numpy-1.26.4 for ARM macos
    result = result.replace(
        "0x24aae0 <_xerbla_64_.format+0x1c0>",
        "xor_to_negate_second"
    )
    (pathlib.Path(__file__).parent / "cdouble_square.s").write_text(header + result)
